---
abstract: 'Alarm Clock in Padre'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-Alarm
provides:
  Padre::Plugin::Alarm:
    file: lib/Padre/Plugin/Alarm.pm
    version: 0.08
requires:
  Audio::Beep: 0
  File::ShareDir: 1.00
  Padre: 0.57
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Alarm/
version: 0.08
